import * as React from "react";
import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
  //Display
  container: {
    flex: 1,
    // paddingHorizontal: '2%',
    backgroundColor: "#F0F8FF",
    alignItems: "center",
    alignContent: "center",
    // justifyContent: 'center',
  },
  containerSlip: {
    flex: 1,
    paddingTop: 10,
    backgroundColor: "#F0F8FF",
    alignItems: "center",
    // justifyContent: 'center',
  },
  containerMap: {
    flex: 1,
    backgroundColor: "#ecf0f1",
    // position: "absolute",
  },
  mapComp: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  map: {
    width: "100%",
    height: "100%",
  },
  scrollView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  text: {
    color: "#828282",
    fontSize: 18,
    // marginVertical: 300,
    fontFamily: "NotoSansThaiMedium",
  },
  how: {
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -60,
  },
  comp: {
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  listItemIcon: {
    fontSize: 40,
    color: "#EF4665",
    fontWeight: "400",
    textAlignVertical: "center",
    marginLeft: 10,
  },
  SwipeIcon: {
    fontSize: 40,
    color: "#EF4665",
    fontWeight: "400",
    marginLeft: "1%",
  },
  DeleteSwipe: {
    marginLeft: "39%",
    backgroundColor: "#BAF0F9",
    width: "17%",
    height: "85%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  EditSwipe: {
    // marginLeft: '47%',
    marginLeft: "1%",
    backgroundColor: "#BAF0F9",
    width: "19%",
    height: "85%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  swipeMain: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    alignContent: "center",
    justifyContent: "center",
    marginTop: 10,
    backgroundColor: "#EF4665",
    // borderColor: '#EF4665',
    // borderWidth: '1%',
    width: "21%",
    height: "89%",
    marginRight: "1%",
    borderRadius: 20,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  swipeMainSearch: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    alignContent: "center",
    justifyContent: "center",
    marginTop: 10,
    backgroundColor: "#EF4665",
    // borderColor: '#EF4665',
    // borderWidth: '1%',
    width: "21%",
    height: "89%",
    marginRight: "2.9%",
    borderRadius: 20,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  swipeList: {
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: 'center',
    marginTop: "5%",
    backgroundColor: "#F0F8FF",
    width: "98%",
    height: 80,
    borderRadius: 15,
    marginLeft: "1%",
  },
  swipeView: {
    // width: '95%',
    // flexDirection: 'row',
    // alignItems: 'center',
    // textAlign: 'center',
  },

  //Button_FAB
  fab: {
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    bottom: 20,
    right: 20,
    backgroundColor: "#1B79DB",
    borderRadius: 100,
    position: "absolute",
  },
  fabIcon: {
    fontSize: 50,
    color: "#fff",
  },
  shadowProp: {
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },

  //Modal
  centeredView: {
    flex: 1,
    justifyContent: "space-evenly",
    alignSelf: "center",
    alignItems: "center",
    width: "95%",
  },
  centeredViewItem: {
    flex: 1,
    justifyContent: "space-evenly",
    alignSelf: "center",
    alignItems: "center",
    width: "100%",
  },
  modalView: {
    width: "95%",
    height: 250,
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    alignItems: "center",
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalViewItem: {
    width: "95%",
    // height: 290,
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    alignItems: "center",
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    fontSize: 20,
    marginBottom: 10,
    textAlign: "center",
    fontWeight: "600",
    paddingTop: 5,
    fontFamily: "NotoSansThaiMedium",
  },
  modalTextNum: {
    fontSize: 18,
    marginBottom: 15,
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "NotoSansThaiMedium",
  },
  textStyle: {
    fontSize: 18,
    color: "#000",
    fontWeight: "600",
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "NotoSansThaiMedium",
  },
  textStyleCel: {
    fontSize: 18,
    color: "white",
    // fontWeight: "bold",
    textAlign: "center",
    fontFamily: "NotoSansThaiMedium",
  },
  picMenu: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    borderWidth: 2,
    borderColor: "#1B79DB",
    alignSelf: "center",
    position: "absolute",
    marginTop: -50,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },

  //Flatlist
  listItemMain: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 10,
    // marginBottom: 2,
    backgroundColor: "#FFFFFF",
    width: "98.5%",
    height: 80,
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 4,
  },
  listItem: {
    flexDirection: "row",
    width: "98%",
    height: 100,
    // paddingHorizontal: 10,
    // justifyContent: 'center',
    alignSelf: "center",
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowRadius: 10,
    shadowOpacity: 0.35,
    elevation: 5,
  },
  listItemHis: {
    flexDirection: "row",
    width: "98%",
    height: 85,
    // paddingHorizontal: 10,
    // justifyContent: 'center',
    alignSelf: "center",
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowRadius: 10,
    shadowOpacity: 0.35,
    elevation: 5,
  },
  selectDT: {
    flexDirection: "row",
    width: "96%",
    height: 70,
    // marginBottom: 15,
    alignSelf: "center",
    alignItems: "center",
    marginTop: 5,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowRadius: 10,
    shadowOpacity: 0.35,
    elevation: 5,
  },
  selectTime: {
    flexDirection: "row",
    width: "41%",
    height: 80,
    backgroundColor: "#BAF0F9",
    // marginBottom: 15,
    alignSelf: "center",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 7,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowRadius: 10,
    shadowOpacity: 0.35,
    elevation: 5,
  },
  listItemShare: {
    flexDirection: "row",
    width: "98%",
    height: 80,
    // paddingHorizontal: 10,
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowRadius: 10,
    shadowOpacity: 0.35,
    elevation: 4,
  },
  listItemView: {
    width: "98%",
    flexDirection: "row",
    alignItems: "center",
  },
  mainlistText: {
    fontSize: 18,
    fontWeight: "400",
    textAlignVertical: "center",
    marginHorizontal: "5%",
    width: "73%",
    fontFamily: "NotoSansThaiMedium",
    // flexDirection: 'row',
  },
  listItemText: {
    fontSize: 18,
    fontWeight: "500",
    marginTop: 10,
    textAlignVertical: "center",
    marginHorizontal: 10,
    width: "75%",
    fontFamily: "NotoSansThaiSemiBold",
    // flexDirection: 'row',
  },
  nameItemShare: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 10,
    textAlignVertical: "center",
    marginHorizontal: 10,
    // paddingTop: 5,
    marginLeft: 20,
    fontFamily: "NotoSansThaiSemiBold",
    // flexDirection: 'row',
  },
  nameItemShareHis: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 10,
    textAlignVertical: "center",
    marginHorizontal: 5,
    marginBottom: 10,
    // paddingTop: 5,
    // marginLeft: 20,
    fontFamily: "NotoSansThaiSemiBold",
    // flexDirection: 'row',
  },
  listShareMain: {
    // flex: 1,
    flexDirection: "row",
    alignSelf: "center",
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    width: "94%",
    // height: 80,
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 4,
  },
  listNoti: {
    // flex: 1,
    flexDirection: "row",
    alignSelf: "center",
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    width: "94%",
    // height: 80,
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 4,
  },
  listSearchMain: {
    flexDirection: "row",
    alignSelf: "center",
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    width: "94%",
    height: 80,
    borderRadius: 15,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 4,
  },
  listItemShareText: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 10,
    textAlignVertical: "center",
    marginHorizontal: 10,
    fontFamily: "NotoSansThaiMedium",
    // flexDirection: 'row',
  },
  unitItemShare: {
    fontSize: 16,
    marginTop: 10,
    textAlignVertical: "center",
    marginHorizontal: 10,
    fontFamily: "NotoSansThaiMedium",
  },
  ItemShareText: {
    fontSize: 18,
    fontWeight: "600",
    // marginTop: 10,
    color: "#fff",
    textAlignVertical: "center",
    marginHorizontal: 10,
    fontFamily: "NotoSansThaiSemiBold",
    // flexDirection: 'row',
  },
  MenulistShareDetail: {
    alignSelf: "flex-start",
  },
  ItemShareProfile: {
    fontSize: 18,
    fontWeight: "600",
    // marginTop: 10,
    color: "#fff",
    // textAlignVertical: 'center',
    marginHorizontal: "5%",
    fontFamily: "NotoSansThaiMedium",
    // flexDirection: 'row',
  },
  priceDetail: {
    // alignSelf: 'flex-end',

    // height: 56,
    marginRight: 25,
    // alignContent: 'center'
  },
  MenulistDetail: {
    width: "96%",
    alignSelf: "flex-start",
    // width: '35%'
    // marginLeft: '2%'
  },
  listShareProfile: {
    justifyContent: "space-between",
    marginRight: -20,
    marginBottom: 10,
    // width: '35%'
  },
  listTextHis: {
    fontSize: 18,
    marginTop: -55,
    flexDirection: "row",
    fontFamily: "NotoSansThaiMedium",
  },
  listItemdateEXP: {
    fontSize: 18,
    fontWeight: "400",
    marginLeft: 80,
    marginTop: -30,
    // fontFamily: 'NotoSansThai-Medium'
  },
  listItemImg: {
    width: 60,
    height: 60,
    borderRadius: 15,
    marginLeft: "3%",
    alignSelf: "center",
  },
  listItemShImg: {
    width: 60,
    height: 60,
    marginLeft: 15,
    marginTop: 10,
  },
  //Icon HistoryScreen
  listIconHis: {
    fontSize: 40,
    color: "#c2c2c2",
    paddingTop: 20,
    marginLeft: 10,
  },

  //Button
  //-Button Modal-
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    // backgroundColor: "#DADADA",
    borderColor: "#DADADA",
    borderWidth: 2,
  },
  //-Button Popup-
  button: {
    width: "43%",
    height: 50,
    borderRadius: 30,
    // padding: 4,
    paddingTop: 10,
    marginHorizontal: "3%",
  },
  buttonmd_Item: {
    width: "43%",
    height: 50,
    borderRadius: 30,
    // padding: 4,
    paddingTop: 10,
    marginTop: 30,
    marginHorizontal: "3%",
  },
  btItem: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: "-4%",
  },
  btFinish: {
    width: "96%",
    height: 50,
    borderRadius: 30,
    backgroundColor: "#DADADA",
    justifyContent: "center",
  },
  btLogin: {
    width: "100%",
    height: 50,
    borderRadius: 30,
    backgroundColor: "#DADADA",
    justifyContent: "center",
  },
  btLocaComp: {
    width: "48%",
    height: 50,
    marginHorizontal: 10,
  },
  btFinishLo: {
    borderRadius: 30,
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: "#EF4665",
  },
  btFinishLoComp: {
    // width: "45%",
    // height: 50,
    borderRadius: 30,
    backgroundColor: "#DADADA",
    justifyContent: "center",
    // marginHorizontal: 15,
  },

  //Text
  //ListScreen
  cardList: {
    width: 358,
    height: 58,
    flexDirection: "row",
  },
  summary: {
    width: "98%",
    justifyContent: "center",
    position: "absolute",
    bottom: 10,
    alignItems: "center",
  },
  summaryLo: {
    width: "98%",
    justifyContent: "center",
    position: "absolute",
    bottom: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  summaryLoComp: {
    width: "98%",
    justifyContent: "center",
    position: "absolute",
    // bottom: 10,
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    paddingHorizontal: "3%",
    paddingTop: "160%",
  },
  textFinish: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333333",
    textAlign: "center",
    fontFamily: "NotoSansThaiMedium",
  },
  textFinishLo: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    fontFamily: "NotoSansThaiMedium",
    justifyContent: "center",
  },
  lineStyle: {
    borderWidth: 1,
    borderColor: "#000",
    margin: 10,
    paddingBottom: 30,
  },
  boxTotal: {
    flexDirection: "row",
    paddingBottom: 25,
    alignSelf: "stretch",
    borderTopWidth: 1,
    borderTopColor: "#c2c2c2",
    paddingTop: 15,
    justifyContent: "space-between",
    // left: 5,
  },
  boxTotalSlip: {
    flexDirection: "row",
    marginBottom: 20,
    borderTopWidth: 1,
    borderTopColor: "#c2c2c2",
    marginTop: 40,
    justifyContent: "space-between",
    // left: 5,
  },
  textTotal: {
    fontSize: 24,
    fontWeight: "500",
    fontFamily: "NotoSansThaiSemiBold",
    // marginLeft: '1%',
    // marginRight: '58%'
  },
  textTotal_2: {
    fontSize: 24,
    fontFamily: "NotoSansThaiSemiBold",
    fontWeight: "500",
    // marginLeft: '60%',
  },

  //CardView
  paragraph: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    fontFamily: "NotoSansThaiMedium",
    padding: 20,
    marginTop: 15,
  },
  CardStyle: {
    width: "90%",
    height: 230,
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 6,
    borderRadius: 15,
    marginHorizontal: "2%",
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  IconStyle: {
    // alignItems: 'center',
    marginTop: 18,
    textAlign: "center",
    // paddingLeft: 4,
  },
  bgIconMenu: {
    width: 120,
    height: 120,
    borderRadius: 120 / 2,
    backgroundColor: "#BAF0F9",
    marginHorizontal: 14,
    marginTop: 30,
  },
  imgMenuCate: {
    height: "100%",
    width: "100%",
    // backgroundColor: '#BAF0F9',
    // borderRadius: '100%',
    // borderRadius: 50,
    alignSelf: "center",
  },
  imgCate: {
    height: "80%",
    width: "90%",
    // backgroundColor: '#BAF0F9',
    // borderRadius: '100%',
    // borderRadius: 50,
    alignSelf: "center",
  },
  container_Card: {
    flex: 1,
    paddingTop: 10,
    flexDirection: "row",
    backgroundColor: "#F0F8FF",
  },
  container_Menu: {
    flex: 1,
    backgroundColor: "#F0F8FF",
  },
  container_Flatlist: {
    flex: 1,
    marginVertical: 20,
  },
  item: {
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    borderRadius: 15,
    marginHorizontal: "2%",
    marginBottom: "5%",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    margin: 1,
  },
  item_Put: {
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 6,
    borderRadius: 15,
    marginHorizontal: "3%",
    marginBottom: "3%",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    margin: 1,
    backgroundColor: "#BAF0F9",
    // height: Dimensions.get('window').width / 2, // approximate a square
  },
  itemInvisible: {
    backgroundColor: "transparent",
  },
  itemText: {
    color: "#fff",
  },
  dropdown: {
    height: 50,
    width: 120,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "#1B79DB",
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    fontFamily: "NotoSansThaiMedium",
  },
  dropdownProfile: {
    width: 90,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "#1B79DB",
  },
  placeholderStyle: {
    fontSize: 16,
    fontWeight: "500",
    color: "#fff",
    fontFamily: "NotoSansThaiMedium",
  },
  selectedTextStyle: {
    fontSize: 16,
    color: "#fff",
    fontFamily: "NotoSansThaiMedium",
  },

  textStyle_popup: {
    fontSize: 18,
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "NotoSansThaiMedium",
  },
  modalText_popup: {
    fontSize: 18,
    fontWeight: "500",
    marginBottom: 15,
    textAlign: "center",
    paddingBottom: 30,
    fontFamily: "NotoSansThaiMedium",
  },
  input_popup: {
    width: "57%",
    height: 50,
    borderRadius: 10,
    marginRight: 10,
    // marginTop: 30,
    marginBottom: 15,
    borderWidth: 1,
    padding: 10,
    borderColor: "#979797",
    fontFamily: "NotoSansThaiMedium",
  },
  inputPopup2: {
    width: "90%",
    height: "19%",
    borderRadius: 10,
    marginTop: 30,
    marginBottom: 40,
    borderWidth: 1,
    padding: 10,
    borderColor: "#979797",
    fontFamily: "NotoSansThaiMedium",
  },
  inputLogin: {
    backgroundColor: "#fff",
    height: 45,
    marginTop: 5,
  },
  btCreatlist: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  popup: {
    flexDirection: "row",
    height: "18%",
  },

  //searchScreen
  searchBar__unclicked: {
    marginTop: 10,
    padding: 10,
    flexDirection: "row",
    width: "98%",
    backgroundColor: "#fff",
    borderRadius: 20,
    borderColor: "#1B79DB",
    alignItems: "center",
    alignSelf: "center",
    borderWidth: 1.2,
    // alignItems: "center",
  },

  input_search: {
    fontSize: 18,
    marginLeft: 10,
    width: "90%",
    fontFamily: "NotoSansThaiMedium",
  },
  putNum: {
    paddingBottom: 10,
    fontSize: 16,
    fontWeight: "500",
    alignSelf: "flex-start",
    fontFamily: "NotoSansThaiMedium",
  },
  putNumlist: {
    paddingBottom: 10,
    fontSize: 16,
    fontWeight: "500",
    alignSelf: "flex-start",
    fontFamily: "NotoSansThaiMedium",
  },
  unitSet: {
    paddingBottom: 10,
    textAlign: "left",
    alignSelf: "flex-start",
    height: 180,
  },
  unitSetShare: {
    paddingBottom: 10,
    textAlign: "left",
    alignSelf: "flex-start",
    height: 240,
    alignItems: "center",
  },
  btUnit2: {
    width: "33%",
    height: "82%",
    borderRadius: 30,
    padding: 10,
    marginHorizontal: "3.5%",
    marginVertical: "2%",
    borderWidth: 1.5,
    borderColor: "#c2c2c2",
  },
  unit: {
    marginBottom: 10,
    fontSize: 16,
    fontWeight: "500",
    // textAlign: 'left',
    alignSelf: "flex-start",
    //  marginLeft: 5,
    marginTop: 5,
    marginBottom: 20,
    fontFamily: "NotoSansThaiMedium",
  },
  unitDetail: {
    marginBottom: 10,
    marginTop: "15%",
    fontSize: 16,
    fontWeight: "500",
    // textAlign: 'left',
    alignSelf: "flex-start",
    fontFamily: "NotoSansThaiMedium",
  },
  btUnit: {
    width: "26%",
    height: "10%",
    borderRadius: 30,
    padding: 10,
    marginHorizontal: "3.5%",
    marginVertical: "2%",
    borderWidth: 1.5,
    borderColor: "#c2c2c2",
  },
  btUnitShare: {
    width: "26%",
    height: "10%",
    borderRadius: 30,
    padding: 10,
    marginHorizontal: 10,
    marginVertical: "2%",
    borderWidth: 1.5,
    borderColor: "#c2c2c2",
  },
  btUnitShare2: {
    width: "26%",
    height: "82%",
    borderRadius: 30,
    padding: 10,
    marginHorizontal: 10,
    marginVertical: "2%",
    borderWidth: 1.5,
    borderColor: "#c2c2c2",
  },
  btUnitDetail: {
    width: "20%",
    height: "15%",
    justifyContent: "center",
    borderRadius: 30,
    padding: 4,
    marginHorizontal: "3.5%",
    marginVertical: "1%",
    borderWidth: 1.5,
    borderColor: "#c2c2c2",
  },
  textUnit: {
    fontSize: 16,
    textAlign: "center",
    fontFamily: "NotoSansThaiMedium",
  },

  //Profile
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 120 / 2,
    borderWidth: 4,
    borderColor: "white",
    marginBottom: 10,
    alignSelf: "center",
    position: "absolute",
    marginTop: 20,
  },
  bodyContent: {
    // flex: 1,
    flexDirection: "row",
    alignItems: "center",
    padding: 30,
  },
  name: {
    fontSize: 24,
    color: "#696969",
    fontWeight: "600",
    fontFamily: "NotoSansThaiMedium",
  },
  info: {
    fontSize: 16,
    color: "#00BFFF",
    marginTop: 5,
    fontFamily: "NotoSansThaiMedium",
  },
  buttonContent: {
    marginTop: 10,
    height: 80,
    width: 80,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderRadius: 100,
    backgroundColor: "#BAF0F9",
  },
  Yourname: {
    alignItems: "center",
    paddingTop: 150,
  },
  point: {
    fontSize: 26,
    color: "#696969",
    fontWeight: "500",
    textAlign: "center",
    paddingTop: 5,
    fontFamily: "NotoSansThaiMedium",
  },
  IconProfile: {
    alignItems: "center",
    color: "#1B79DB",
    fontSize: 50,
  },

  //CreateShareScreen
  buttonContainer: {
    backgroundColor: "#fff",
    alignSelf: "flex-end",
  },
  preview: {
    alignSelf: "stretch",
    flex: 1,
  },
  btCamera: {
    width: 100,
    height: 100,
    backgroundColor: "#BAF0F9",
    borderRadius: 100 / 2,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#1B79DB",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  buttonContainer: {},
  inputCreateSh: {
    width: 358,
    borderBottomWidth: 0.5,
    borderBottomColor: "#000",
    paddingTop: 30,
    textAlign: "center",
    fontSize: 24,
    fontFamily: "NotoSansThaiMedium",
  },
  detailMenu: {
    justifyContent: "center",
    paddingLeft: 20,
    paddingTop: 25,
    alignSelf: "flex-start",
  },
  putAmount: {
    // paddingRight: 220,
    paddingBottom: 10,
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "NotoSansThaiMedium",
  },
  calendar: {
    width: 358,
    height: 50,
    borderWidth: 0.5,
    borderRadius: 10,
    padding: 8,
    flexDirection: "row",
    marginBottom: 25,
  },
  dateEXP: {
    fontSize: 16,
    padding: 5,
    marginLeft: 5,
    fontFamily: "NotoSansThaiMedium",
  },

  //MainListScreen
  titleList: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333333",
    fontFamily: "NotoSansThaiMedium",
  },

  //SlipScreen
  slip_Boxx: {
    width: "96%",
    // height: 'auto',
    backgroundColor: "#BAF0F9",
    padding: 15,
    marginTop: 10,
    marginHorizontal: "2%",
    borderRadius: 10,
  },
  slip_Box: {
    width: "95%",
    // height: 'auto',
    backgroundColor: "#BAF0F9",
    padding: 15,
    marginTop: 10,
    borderRadius: 10,
  },
  date_time: {
    fontSize: 16,
    fontFamily: "NotoSansThaiMedium",
    fontWeight: "600",
    marginBottom: 4,
    paddingLeft: 50,
  },
  logoSlip: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
    borderWidth: 1,
    borderColor: "#fff",
    backgroundColor: "#fff",
    position: "absolute",
  },
  detailList: {
    width: "99%",
    flexDirection: "row",
    justifyContent: "space-between",
    // alignItems: 'center',
  },

  animate: {
    width: 400,
    height: 400,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 5,
    // marginLeft:'7%'
  },
  animatecomp: {
    width: 300,
    height: 300,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
    // marginLeft:'7%'
  },
  animateSearch: {
    width: 180,
    height: 180,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    // marginBottom: 5,
    // marginLeft:'7%'
  },
  boxAni: {
    marginTop: "25%",
  },
  sectionStyle: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderBottomWidth: 0.5,
    borderColor: "#000",
    height: 40,
    borderRadius: 5,
    margin: 10,
  },

  //login
  iconStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: "stretch",
    alignItems: "center",
  },
  groupChildShadowBox: {
    width: "20%",
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadow0ffset: {
      width: 0,
      height: 1,
    },
    shadowColor: "rgba(0, 0, 0, 0.25)",
    backgroundColor: "#0e4d90",
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    top: 0,
    position: "absolute",
    height: "90%",
  },
  groupItemShadowBox: {
    backgroundColor: "#fff",
    width: "20%",
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadow0ffset: {
      width: 0,
      height: 1,
    },
    shadowColor: "rgba(0, 0, 0, 0.25)",
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    top: 0,
    position: "absolute",
    height: "90%",
  },
  groupChild: {
    left: 0,
  },
  groupItem: {
    left: 78,
  },
  groupInner: {
    left: 156,
  },
  rectangleView: {
    left: 234,
  },
  groupChild1: {
    left: 312,
  },
  rectangleParent: {
    width: 390,
    height: 80,
  },
  titleText: {
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 8,
    fontFamily: "NotoSansThaiMedium",
  },
  titleTextDe: {
    fontSize: 16,
    // fontWeight: '500',
    marginBottom: 8,
    fontFamily: "NotoSansThaiMedium",
  },
});
export default styles;
